#!/bin/bash

# run screensaver in background so we can do 'xscreensaver-command
# -lock'

xscreensaver &

# keyboard settings

setxkbmap 'gb(dvorak)' -option 'ctrl:nocaps'

# background image

feh --bg-fill ~/.xmonad/wallpaper.jpg

# daemonized emacs process launch

emacs --daemon
